/* automatically generated by rust-bindgen 0.71.1 */

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum AppEvent {
    LOAD = 0,
    UNLOAD = 1,
    NOTIFY = 2,
    HOOK = 3,
    META = 4
}
#[repr(C)]
#[derive(Debug)]
pub struct App {
    _unused: [u8; 0]
}
pub type AppModule = ::core::option::Option<
    unsafe extern "C" fn(
        arg1: *const App,
        arg2: *const AppEvent,
        arg3: *const *const ::core::ffi::c_void
    ) -> *const ::core::ffi::c_void
>;
unsafe extern "C" {
    pub static ERR_APP: isize;
}
unsafe extern "C" {
    pub static MOD_ENV: AppModule;
}
unsafe extern "C" {
    pub static MOD_LOG: AppModule;
}
unsafe extern "C" {
    pub static MOD_CONFIG: AppModule;
}
unsafe extern "C" {
    pub static MOD_CMD: AppModule;
}
unsafe extern "C" {
    pub static MOD_LD: AppModule;
}
unsafe extern "C" {
    pub static MOD_HELP: AppModule;
}
unsafe extern "C" {
    pub static MOD_ASYNC: AppModule;
}
unsafe extern "C" {
    pub fn app_new(
        modules: *const AppModule,
        count: ::core::ffi::c_uint,
        argc: ::core::ffi::c_int,
        argv: *const *const ::core::ffi::c_char
    ) -> *const App;
}
unsafe extern "C" {
    pub fn app_run(
        app: *const App,
        context: *const ::core::ffi::c_void
    ) -> *const *const ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn app_notify(
        app: *const App,
        notify: *const ::core::ffi::c_char,
        sender: *const ::core::ffi::c_void,
        context: *const ::core::ffi::c_void
    ) -> *const *const ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn app_free(app: *const App);
}
unsafe extern "C" {
    pub fn app_set_default_cmd(cmd: *const ::core::ffi::c_char);
}
unsafe extern "C" {
    pub fn app_set_event_handled(event: *const AppEvent, handled: bool);
}
unsafe extern "C" {
    pub fn app_get_event_notify(event: *const AppEvent) -> *mut ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn app_load_module(app: *const App, module: AppModule);
}
unsafe extern "C" {
    pub fn app_unload_module(app: *const App, module: AppModule);
}
unsafe extern "C" {
    pub fn app_error(err: *const ::core::ffi::c_char) -> *const ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn app_add_notify_handler(
        app: *const App,
        notify: *const ::core::ffi::c_char,
        module: AppModule
    ) -> bool;
}
unsafe extern "C" {
    pub fn app_remove_notify_handler(
        app: *const App,
        notify: *const ::core::ffi::c_char,
        module: AppModule
    ) -> bool;
}
unsafe extern "C" {
    pub fn app_add_hook_handler(
        app: *const App,
        event: AppEvent,
        notify: *const ::core::ffi::c_char,
        module: AppModule
    ) -> bool;
}
unsafe extern "C" {
    pub fn app_remove_hook_handler(
        app: *const App,
        event: AppEvent,
        notify: *const ::core::ffi::c_char,
        module: AppModule
    ) -> bool;
}
